name: Build EXE
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Ενημερωμένη έκδοση

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Χρησιμοποιούμε την πιο σταθερή έκδοση 20

      - name: Install dependencies
        run: npm install

      - name: Build EXE
        run: npm run make
