name: Build EXE
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install --no-package-lock
          npm install --save-dev @electron-forge/cli @electron-forge/maker-squirrel @electron-forge/maker-zip

      - name: Build EXE
        run: npm run make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SNR-Application
          path: out/make/squirrel.windows/x64/*.exe
